### ISSUE TITLE
The specified deps.json does not exist

### ISSUE THREAD

**Issue by czifro** [dotnet/netcorecli-fsc#41] opened 2016-11-18 20:11 UTC
I have been trying to get F# working on my mac using dotnet preview3-004056 and this repo. I am trying to get the preview3 console app to build but keep getting the following error: `The specified deps.json [/Users/czifro/.nuget/packages/.tools/dotnet-compile-fsc/1.0.0-preview2-020000/netcoreapp1.0/dotnet-compile-fsc.deps.json] does not exist` I performed a restore, so that couldn't be an issue (right?). Anyways these are the exact steps I did:

1. Fetched dotnet @ https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview3-004056/dotnet-dev-osx-x64.1.0.0-preview3-004056.tar.gz
2. Copied binaries to `/usr/local/share` 
3. Asserted dotnet works with `dotnet --version` and got `1.0.0-preview3-004056`
4. Cloned this repo and went to `preview3/console` example
5. Ran `dotnet restore; dotnet build`

Here is the full output of both `restore` and `build`:
```
MacBook-Pro:console czifro$ dotnet restore
  Restoring packages for /Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/ExampleConsoleApp.fsproj...
  Restoring packages for /Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/ExampleConsoleApp.fsproj...
  Restore completed in 527.8931ms for /Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/ExampleConsoleApp.fsproj.
  Lock file has not changed. Skipping lock file write. Path: /Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/obj/project.assets.json
  Generating MSBuild file /Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/obj/ExampleConsoleApp.fsproj.nuget.g.targets.
  Generating MSBuild file /Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/obj/ExampleConsoleApp.fsproj.nuget.g.props.
  Restore completed in 1826.2184ms for /Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/ExampleConsoleApp.fsproj.
  
  NuGet Config files used:
      /Users/czifro/.nuget/NuGet/NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json
MacBook-Pro:console czifro$ dotnet build
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 11/17/16 9:32:16 PM.
     1>Project "/Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/ExampleConsoleApp.fsproj" on node 1 (Build target(s)).
     1>CoreCompile:
         dotnet exec --depsfile /Users/czifro/.nuget/packages/.tools/dotnet-compile-fsc/1.0.0-preview2-020000/netcoreapp1.0/dotnet-compile-fsc.deps.json --additionalprobingpath /Users/czifro/.nuget/packages /Users/czifro/.nuget/packages/dotnet-compile-fsc/1.0.0-preview2-020000/lib/netcoreapp1.0/dotnet-compile-fsc.dll @/Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/obj/Debug/netcoreapp1.0/dotnet-compile.rsp
         The specified deps.json [/Users/czifro/.nuget/packages/.tools/dotnet-compile-fsc/1.0.0-preview2-020000/netcoreapp1.0/dotnet-compile-fsc.deps.json] does not exist
     1>/Users/czifro/.nuget/packages/fsharp.net.sdk/1.0.0-alpha-000007/build/netstandard1.0/FSharp.NET.Core.Sdk.targets(141,9): error MSB3073: The command "dotnet exec --depsfile /Users/czifro/.nuget/packages/.tools/dotnet-compile-fsc/1.0.0-preview2-020000/netcoreapp1.0/dotnet-compile-fsc.deps.json --additionalprobingpath /Users/czifro/.nuget/packages /Users/czifro/.nuget/packages/dotnet-compile-fsc/1.0.0-preview2-020000/lib/netcoreapp1.0/dotnet-compile-fsc.dll @/Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/obj/Debug/netcoreapp1.0/dotnet-compile.rsp" exited with code 129. [/Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/ExampleConsoleApp.fsproj]
     1>Done Building Project "/Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/ExampleConsoleApp.fsproj" (Build target(s)) -- FAILED.

Build FAILED.

       "/Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/ExampleConsoleApp.fsproj" (Build target) (1) ->
       (CoreCompile target) -> 
         /Users/czifro/.nuget/packages/fsharp.net.sdk/1.0.0-alpha-000007/build/netstandard1.0/FSharp.NET.Core.Sdk.targets(141,9): error MSB3073: The command "dotnet exec --depsfile /Users/czifro/.nuget/packages/.tools/dotnet-compile-fsc/1.0.0-preview2-020000/netcoreapp1.0/dotnet-compile-fsc.deps.json --additionalprobingpath /Users/czifro/.nuget/packages /Users/czifro/.nuget/packages/dotnet-compile-fsc/1.0.0-preview2-020000/lib/netcoreapp1.0/dotnet-compile-fsc.dll @/Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/obj/Debug/netcoreapp1.0/dotnet-compile.rsp" exited with code 129. [/Users/czifro/Developer/Repositories/netcorecli-fsc/examples/preview3/console/ExampleConsoleApp.fsproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.12
```

Other info that might be useful:

- Mac OS Version: macOS Sierra 10.12.1
- Mono Version: 4.6.1.5, installed with homebrew

**Comment by enricosada** [comment] 2016-11-21 10:01
i can repro, i'll push a fix today

**Comment by enricosada** [comment] 2016-11-21 17:59
I can repro in the windows ci server (and paket windows pr build) too, so affect also windows.
But not locally on my windows machine, but np, is just a bug

**Comment by enricosada** [comment] 2016-11-21 23:05
should be fixed now with version [FSharp.NET.Sdk v1.0.0-alpha-000009](https://www.nuget.org/packages/FSharp.NET.Sdk/1.0.0-alpha-000009)

if you use `1.0.0-alpha-*` in `fsproj`, you just need to redo `dotnet restore`.

I added ci on all os now with #45 so should be ok (i had same issue in ci)

@czifro if is not ok, pls reopen this issue
/cc @alfonsogarciacaro @forki because i think it's the same error you had

**Closed by enricosada** 2016-11-21 23:05 UTC

**Comment by alfonsogarciacaro** [comment] 2016-11-22 00:29
I can confirm it's working for me on Mac now (I had indeed the same error before). Thanks a lot @enricosada!

**Comment by czifro** [comment] 2016-11-22 00:34
It is working for me as well. Thanks!
