### ISSUE TITLE
Add more template

### ISSUE THREAD

**Issue by aloisdg** [dotnet/netcorecli-fsc#21] opened 2016-11-04 08:50 UTC
Hello,

I would enjoy to have the possiblity to do `dotnet new -l F# -t Lib` or `-t xunittest`. I think I could use [aspnet generator](https://github.com/OmniSharp/generator-aspnet), but I would prefer to use dotnet cli like I do in C#.

Thanks you for your work!

Cheers,

**Comment by odytrice** [comment] 2016-11-12 07:28
I've been looking into this issue. I think you should raise it at dotnetcore cli repo https://github.com/dotnet/cli/issues I wasn't sure how to contribute it there that's why I did the added it to the aspnet generator instead.

**Comment by enricosada** [comment] 2016-11-15 16:40
Logged into another issue

Closing as dupe of #36

**Closed by enricosada** 2016-11-15 16:40 UTC
Labels: duplicate
