### ISSUE TITLE
we need a fsc that runs on netcoreapp2.0

### ISSUE THREAD

**Issue by livarcocc** [dotnet/netcorecli-fsc#92] opened 2017-03-10 06:34 UTC
This is blocking F# from working in the 2.0 CLI.

**Comment by enricosada** [comment] 2017-03-12 16:16
@livarcocc `dotnet-compile-fsc` is not used anymore.
it's not in net core 1.0 templates either.

Atm there is not a f# compiler (`fsc`) built for .net core 2.0.

**Comment by eerhardt** [comment] 2017-03-20 16:29
Is this issue a duplicate of https://github.com/dotnet/netcorecli-fsc/issues/76?

**Comment by enricosada** [comment] 2017-03-20 16:50
@eerhardt related, we need also `netcoreapp2.0` fsc. #76 need `netcoreapp1.1`. 
And in common is a way to list avaiable fsc from `FSharp.Compiler.Tools` nupkg and choose one (that will be useful for `net45` fsc too)

It can be done easier after vf# move to sdk 1.0 rtm, that's the main blocker (atm is preview2), i am going to work on that this week

Or 2.0 cli has also .net core 1.1 runtime bundled?

**Comment by eerhardt** [comment] 2017-03-20 16:54
> Or 2.0 cli has also .net core 1.1 runtime bundled?

Not for all RIDs.  I'm standing up the `linux-x64` RID now, which only works on .NET Core 2.0, so there is no 1.0 or 1.1 runtimes for that RID.

Also, our current plan is that when the .NET Core 2.0 SDK ships, it will only contain the 2.0 runtime. There won't be any "additional runtimes" in the box.

So we will need F# to work when only 2.0 is installed.

**Comment by enricosada** [comment] 2017-06-13 15:19
Closing.

- `Fsharp.NET.Sdk` is deprecated for sdk 2.0 (see https://github.com/dotnet/netcorecli-fsc/issues/108#issuecomment-308150566 ) 
- `fsc` will bundled with sdks, not from `FSharp.Compiler.Tools` (ref https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1032-fsharp-in-dotnet-sdk.md)

**Closed by enricosada** 2017-06-13 15:19 UTC
Labels: bug, msbuild
