### ISSUE TITLE
Can not build .Net Core F# project on Ubuntu 16.10

### ISSUE THREAD

**Issue by JacobChang** [dotnet/netcorecli-fsc#104] opened 2017-04-24 10:14 UTC
**Reproduce steps**

Install .NET Core latest version  (following [instructions](https://www.microsoft.com/net/core#linuxubuntu), I tried both dotnet-dev-1.0.1 and dotnet-dev-1.0.3 on Ubunut 16.10, the output will differ when running dotnet commands, but the build error is the same)

```
dotnet new console -lang F# -o Test

cd Test

dotnet restore

dotnet build

```

**Expected behavior**

build the project successfully

**Actual behavior**

```
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

/home/ubuntu/.nuget/packages/fsharp.net.sdk/1.0.2/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet" exited with code 131. [/home/ubuntu/Projects/Test/Test.fsproj]

Build FAILED.

/home/ubuntu/.nuget/packages/fsharp.net.sdk/1.0.2/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet" exited with code 131. [/home/ubuntu/Projects/Test/Test.fsproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.42
```

**Details**

```
dotnet --info

.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.10
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.3

```

```
dotnet build -v n

Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/24/17 6:11:41 PM.
Project "/home/ubuntu/Projects/Test/Test.fsproj" on node 1 (Build target(s)).
CoreCompile:
  /usr/share/dotnet/sdk/1.0.3/Sdks/../../../dotnet  "/home/ubuntu/.nuget/packages/fsharp.compiler.tools/4.1.1/build/netcoreapp1.0/fsc.dll" -o:obj/Debug/netcoreapp1.1/Test.dll
  -g
  --debug:portable
  --noframework
  --define:DEBUG
  --define:NETCOREAPP1_1
  --optimize-
  -r:/home/ubuntu/.nuget/packages/fsharp.core/4.1.12/lib/netstandard1.6/FSharp.Core.dll
  -r:/home/ubuntu/.nuget/packages/microsoft.csharp/4.3.0/ref/netstandard1.0/Microsoft.CSharp.dll
  -r:/home/ubuntu/.nuget/packages/microsoft.visualbasic/10.1.0/ref/netstandard1.1/Microsoft.VisualBasic.dll
  -r:/home/ubuntu/.nuget/packages/microsoft.win32.primitives/4.3.0/ref/netstandard1.3/Microsoft.Win32.Primitives.dll
  -r:/home/ubuntu/.nuget/packages/system.appcontext/4.3.0/ref/netstandard1.6/System.AppContext.dll
  -r:/home/ubuntu/.nuget/packages/system.buffers/4.3.0/lib/netstandard1.1/System.Buffers.dll
  -r:/home/ubuntu/.nuget/packages/system.collections.concurrent/4.3.0/ref/netstandard1.3/System.Collections.Concurrent.dll
  -r:/home/ubuntu/.nuget/packages/system.collections/4.3.0/ref/netstandard1.3/System.Collections.dll
  -r:/home/ubuntu/.nuget/packages/system.collections.immutable/1.3.0/lib/netstandard1.0/System.Collections.Immutable.dll
  -r:/home/ubuntu/.nuget/packages/system.componentmodel.annotations/4.3.0/ref/netstandard1.4/System.ComponentModel.Annotations.dll
  -r:/home/ubuntu/.nuget/packages/system.componentmodel/4.3.0/ref/netstandard1.0/System.ComponentModel.dll
  -r:/home/ubuntu/.nuget/packages/system.console/4.3.0/ref/netstandard1.3/System.Console.dll
  -r:/home/ubuntu/.nuget/packages/system.diagnostics.debug/4.3.0/ref/netstandard1.3/System.Diagnostics.Debug.dll
  -r:/home/ubuntu/.nuget/packages/system.diagnostics.diagnosticsource/4.3.0/lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll
  -r:/home/ubuntu/.nuget/packages/system.diagnostics.process/4.3.0/ref/netstandard1.4/System.Diagnostics.Process.dll
  -r:/home/ubuntu/.nuget/packages/system.diagnostics.tools/4.3.0/ref/netstandard1.0/System.Diagnostics.Tools.dll
  -r:/home/ubuntu/.nuget/packages/system.diagnostics.tracing/4.3.0/ref/netstandard1.5/System.Diagnostics.Tracing.dll
  -r:/home/ubuntu/.nuget/packages/system.dynamic.runtime/4.3.0/ref/netstandard1.3/System.Dynamic.Runtime.dll
  -r:/home/ubuntu/.nuget/packages/system.globalization.calendars/4.3.0/ref/netstandard1.3/System.Globalization.Calendars.dll
  -r:/home/ubuntu/.nuget/packages/system.globalization/4.3.0/ref/netstandard1.3/System.Globalization.dll
  -r:/home/ubuntu/.nuget/packages/system.globalization.extensions/4.3.0/ref/netstandard1.3/System.Globalization.Extensions.dll
  -r:/home/ubuntu/.nuget/packages/system.io.compression/4.3.0/ref/netstandard1.3/System.IO.Compression.dll
  -r:/home/ubuntu/.nuget/packages/system.io.compression.zipfile/4.3.0/ref/netstandard1.3/System.IO.Compression.ZipFile.dll
  -r:/home/ubuntu/.nuget/packages/system.io/4.3.0/ref/netstandard1.5/System.IO.dll
  -r:/home/ubuntu/.nuget/packages/system.io.filesystem/4.3.0/ref/netstandard1.3/System.IO.FileSystem.dll
  -r:/home/ubuntu/.nuget/packages/system.io.filesystem.primitives/4.3.0/ref/netstandard1.3/System.IO.FileSystem.Primitives.dll
  -r:/home/ubuntu/.nuget/packages/system.io.filesystem.watcher/4.3.0/ref/netstandard1.3/System.IO.FileSystem.Watcher.dll
  -r:/home/ubuntu/.nuget/packages/system.io.memorymappedfiles/4.3.0/ref/netstandard1.3/System.IO.MemoryMappedFiles.dll
  -r:/home/ubuntu/.nuget/packages/system.io.unmanagedmemorystream/4.3.0/ref/netstandard1.3/System.IO.UnmanagedMemoryStream.dll
  -r:/home/ubuntu/.nuget/packages/system.linq/4.3.0/ref/netstandard1.6/System.Linq.dll
  -r:/home/ubuntu/.nuget/packages/system.linq.expressions/4.3.0/ref/netstandard1.6/System.Linq.Expressions.dll
  -r:/home/ubuntu/.nuget/packages/system.linq.parallel/4.3.0/ref/netstandard1.1/System.Linq.Parallel.dll
  -r:/home/ubuntu/.nuget/packages/system.linq.queryable/4.3.0/ref/netstandard1.0/System.Linq.Queryable.dll
  -r:/home/ubuntu/.nuget/packages/system.net.http/4.3.0/ref/netstandard1.3/System.Net.Http.dll
  -r:/home/ubuntu/.nuget/packages/system.net.nameresolution/4.3.0/ref/netstandard1.3/System.Net.NameResolution.dll
  -r:/home/ubuntu/.nuget/packages/system.net.primitives/4.3.0/ref/netstandard1.3/System.Net.Primitives.dll
  -r:/home/ubuntu/.nuget/packages/system.net.requests/4.3.0/ref/netstandard1.3/System.Net.Requests.dll
  -r:/home/ubuntu/.nuget/packages/system.net.security/4.3.0/ref/netstandard1.3/System.Net.Security.dll
  -r:/home/ubuntu/.nuget/packages/system.net.sockets/4.3.0/ref/netstandard1.3/System.Net.Sockets.dll
  -r:/home/ubuntu/.nuget/packages/system.net.webheadercollection/4.3.0/ref/netstandard1.3/System.Net.WebHeaderCollection.dll
  -r:/home/ubuntu/.nuget/packages/system.numerics.vectors/4.3.0/ref/netstandard1.0/System.Numerics.Vectors.dll
  -r:/home/ubuntu/.nuget/packages/system.objectmodel/4.3.0/ref/netstandard1.3/System.ObjectModel.dll
  -r:/home/ubuntu/.nuget/packages/system.reflection.dispatchproxy/4.3.0/ref/netstandard1.3/System.Reflection.DispatchProxy.dll
  -r:/home/ubuntu/.nuget/packages/system.reflection/4.3.0/ref/netstandard1.5/System.Reflection.dll
  -r:/home/ubuntu/.nuget/packages/system.reflection.extensions/4.3.0/ref/netstandard1.0/System.Reflection.Extensions.dll
  -r:/home/ubuntu/.nuget/packages/system.reflection.metadata/1.4.1/lib/netstandard1.1/System.Reflection.Metadata.dll
  -r:/home/ubuntu/.nuget/packages/system.reflection.primitives/4.3.0/ref/netstandard1.0/System.Reflection.Primitives.dll
  -r:/home/ubuntu/.nuget/packages/system.reflection.typeextensions/4.3.0/ref/netstandard1.5/System.Reflection.TypeExtensions.dll
  -r:/home/ubuntu/.nuget/packages/system.resources.reader/4.3.0/lib/netstandard1.0/System.Resources.Reader.dll
  -r:/home/ubuntu/.nuget/packages/system.resources.resourcemanager/4.3.0/ref/netstandard1.0/System.Resources.ResourceManager.dll
  -r:/home/ubuntu/.nuget/packages/system.runtime/4.3.0/ref/netstandard1.5/System.Runtime.dll
  -r:/home/ubuntu/.nuget/packages/system.runtime.extensions/4.3.0/ref/netstandard1.5/System.Runtime.Extensions.dll
  -r:/home/ubuntu/.nuget/packages/system.runtime.handles/4.3.0/ref/netstandard1.3/System.Runtime.Handles.dll
  -r:/home/ubuntu/.nuget/packages/system.runtime.interopservices/4.3.0/ref/netcoreapp1.1/System.Runtime.InteropServices.dll
  -r:/home/ubuntu/.nuget/packages/system.runtime.interopservices.runtimeinformation/4.3.0/ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll
  -r:/home/ubuntu/.nuget/packages/system.runtime.numerics/4.3.0/ref/netstandard1.1/System.Runtime.Numerics.dll
  -r:/home/ubuntu/.nuget/packages/system.security.cryptography.algorithms/4.3.0/ref/netstandard1.6/System.Security.Cryptography.Algorithms.dll
  -r:/home/ubuntu/.nuget/packages/system.security.cryptography.encoding/4.3.0/ref/netstandard1.3/System.Security.Cryptography.Encoding.dll
  -r:/home/ubuntu/.nuget/packages/system.security.cryptography.primitives/4.3.0/ref/netstandard1.3/System.Security.Cryptography.Primitives.dll
  -r:/home/ubuntu/.nuget/packages/system.security.cryptography.x509certificates/4.3.0/ref/netstandard1.4/System.Security.Cryptography.X509Certificates.dll
  -r:/home/ubuntu/.nuget/packages/system.security.principal/4.3.0/ref/netstandard1.0/System.Security.Principal.dll
  -r:/home/ubuntu/.nuget/packages/system.text.encoding/4.3.0/ref/netstandard1.3/System.Text.Encoding.dll
  -r:/home/ubuntu/.nuget/packages/system.text.encoding.extensions/4.3.0/ref/netstandard1.3/System.Text.Encoding.Extensions.dll
  -r:/home/ubuntu/.nuget/packages/system.text.regularexpressions/4.3.0/ref/netcoreapp1.1/System.Text.RegularExpressions.dll
  -r:/home/ubuntu/.nuget/packages/system.threading/4.3.0/ref/netstandard1.3/System.Threading.dll
  -r:/home/ubuntu/.nuget/packages/system.threading.tasks.dataflow/4.7.0/lib/netstandard1.1/System.Threading.Tasks.Dataflow.dll
  -r:/home/ubuntu/.nuget/packages/system.threading.tasks/4.3.0/ref/netstandard1.3/System.Threading.Tasks.dll
  -r:/home/ubuntu/.nuget/packages/system.threading.tasks.extensions/4.3.0/lib/netstandard1.0/System.Threading.Tasks.Extensions.dll
  -r:/home/ubuntu/.nuget/packages/system.threading.tasks.parallel/4.3.0/ref/netstandard1.1/System.Threading.Tasks.Parallel.dll
  -r:/home/ubuntu/.nuget/packages/system.threading.thread/4.3.0/ref/netstandard1.3/System.Threading.Thread.dll
  -r:/home/ubuntu/.nuget/packages/system.threading.threadpool/4.3.0/ref/netstandard1.3/System.Threading.ThreadPool.dll
  -r:/home/ubuntu/.nuget/packages/system.threading.timer/4.3.0/ref/netstandard1.2/System.Threading.Timer.dll
  -r:/home/ubuntu/.nuget/packages/system.xml.readerwriter/4.3.0/ref/netstandard1.3/System.Xml.ReaderWriter.dll
  -r:/home/ubuntu/.nuget/packages/system.xml.xdocument/4.3.0/ref/netstandard1.3/System.Xml.XDocument.dll
  --target:exe
  --warn:4
  --warnaserror:76
  --fullpaths
  --flaterrors
  --highentropyva-
  --targetprofile:netcore
  --simpleresolution
  --nocopyfsharpcore
  /home/ubuntu/Projects/Test/Program.fs
  
  The specified framework 'Microsoft.NETCore.App', version '1.0.1' was not found.
    - Check application dependencies and target a framework version installed at:
        /usr/share/dotnet/shared/Microsoft.NETCore.App
    - The following versions are installed:
        1.1.1
    - Alternatively, install the framework version '1.0.1'.
/home/ubuntu/.nuget/packages/fsharp.net.sdk/1.0.2/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet" exited with code 131. [/home/ubuntu/Projects/Test/Test.fsproj]
GenerateBuildDependencyFile:
Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.
Done Building Project "/home/ubuntu/Projects/Test/Test.fsproj" (Build target(s)) -- FAILED.

Build FAILED.

"/home/ubuntu/Projects/Test/Test.fsproj" (Build target) (1) ->
(CoreCompile target) -> 
  /home/ubuntu/.nuget/packages/fsharp.net.sdk/1.0.2/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet" exited with code 131. [/home/ubuntu/Projects/Test/Test.fsproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.19

```

It looks like there's a similar issus https://github.com/dotnet/netcorecli-fsc/issues/42

**Comment by enricosada** [comment] 2017-04-24 15:31
Hi @JacobChang , the issue is a duplicated of #91 

Ubuntu 16.10 support only .net core runtime 1.1, and doesn't exist yet a fsc (f# compiler) who runs on that. 
The all other sdk bundle of 1.1 embedd both the 1.0 runtime and 1.1 (so f# works)

Atm the only workaround is install the 1.0 ( ref https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0.1#net-core-111-for-ubuntu-1610-fails-to-build-f-projects )

Will be fixed with #76 and #91

**Closed by enricosada** 2017-04-24 15:31 UTC
