### ISSUE TITLE
Cannot reference a project with spaces in the path

### ISSUE THREAD

**Issue by alfonsogarciacaro** [dotnet/netcorecli-fsc#67] opened 2017-02-04 22:43 UTC
1.0.0-rc3-004530
FSharp.NET.Sdk/1.0.0-beta-050000

I add a project reference using a path containing spaces, this works correctly in the CLI: `dotnet add reference ../Project With Spaces/Fable.Tests.Spaces.fsproj`

However when I build the project, I get the following error: `Response file 'C:\Users\Alfonso\dev\Fable\src\tests\Project' doesn't exist.`

I successfully built a C# project with a reference containing spaces so this seems to be a problem of the F# SDK.

**Comment by ErikSchierboom** [comment] 2017-02-07 11:57
I think this is a duplicate of #59

**Comment by enricosada** [comment] 2017-02-07 14:11
yes, it's a dupe. I'll fix soon (today or tomorrow) with an updated `FSharp.NET.Sdk` ( ref #68 )

**Closed by enricosada** 2017-02-07 14:11 UTC
Labels: bug
